### ISSUE TITLE
margin* arguments seem to be ignored

### ISSUE THREAD

**Issue by ruidc** [dataverity/chromehtml2pdf#1]
Hi I'm running via docker in latest alpine container with alpine-repo version of chromium.
I can see it recognised my marginLeft=2 argument in the print statement:
```
Converting file: file:///home/pptruser/mnt/company/scorecard.html
out = mnt/company/company_scorecard.pdf
printBackground = true
format = A4
marginLeft = 2
Using chrome executable: /usr/bin/chromium-browser
```
but am definitely not getting 2 inch margin, no matter what value I place there the PDF is the same.

**Comment by ruidc** [comment]
It seems units need to be passed in addition to number, specifying all of marginLeft/marginTop/marginBottom/marginRight with value of 2in works. Sorry for the noise.

**Comment by juacala** [comment]
The documentation was poor on this. We copied it originally from the puppeteer's documentation for the PDF interface. We updated it so that it's clear you need to include units for it to work. Thanks for the post!
